export const headers = [
    { name: "Entry #", field: "entry", sortable: true },
    { name: "Date Created", field: "date_created", sortable: true },
    { name: "IP Address", field: "ip_address", sortable: true },
    { name: "Name - First", field: "first_name", sortable: true },
    { name: "Name - Last", field: "last_name", sortable: true },
    { name: "Age", field: "age", sortable: true },
    { name: "Mobile Number", field: "mobile_number", sortable: true },
    { name: "Email", field: "email", sortable: true },
    { name: "Time Slot", field: "time_slot", sortable: true },
    { name: "SSC / HSC", field: "ssc_hsc", sortable: true },
    { name: "Diploma", field: "diploma", sortable: true },
    { name: "Bachelor", field: "bachelor", sortable: true },
    { name: "Masters", field: "masters", sortable: true },
    { name: "PHD", field: "phd", sortable: true },
    { name: "Profession", field: "profession", sortable: true },
    { name: "1 - 3 Years+ Experience", field: "1_3_year", sortable: true },
    { name: "1 Year Experience", field: "1_year", sortable: true },
    { name: "3 Years+ Experience", field: "3_year", sortable: true },
    { name: "Settlement Fund", field: "settealment_fund", sortable: true },
    { name: "Would you like to invite others?", field: "other_invites", sortable: true },
    { name: "Email Address", field: "email_address", sortable: true },
]